name: Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      elastic:
        image: elasticsearch:7.17.7
        env:
          discovery.type: single-node
          cluster.name: docker-cluster
          ES_JAVA_OPTS: -Xms512m -Xmx512m
        ports:
          - 9200:9200
          - 9300:9300
    strategy:
      fail-fast: false
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
        plone: ["6.0-latest", "5.2-latest"]
        exclude:
          - plone: "5.2-latest"
            python: "3.9"
          - plone: "5.2-latest"
            python: "3.10"
          - plone: "6.0-latest"
            python: "3.7"

    steps:
      # git checkout
      - uses: actions/checkout@v2

      - name: Setup Plone ${{ matrix.plone }} with Python ${{ matrix.python }}
        id: setup
        uses: plone/setup-plone@v1.0.0
        with:
          python-version: ${{ matrix.python }}
          plone-version: ${{ matrix.plone }}

      - name: Install package
        run: |
          pip install -e ".[test, redis]"

      # test
      - name: test
        run: |
          zope-testrunner --auto-color --auto-progress --test-path src
