name: Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7.0.5
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        plone: ["6.0-latest", "5.2-latest"]
        exclude:
          - plone: "5.2-latest"
            python: "3.9"
          - plone: "5.2-latest"
            python: "3.10"
          - plone: "6.0-latest"
            python: "3.7"

    steps:
      # git checkout
      - uses: actions/checkout@v2

      - name: Setup opensearch docker container with ingest attachment plugin
        run: |
          docker container create --name opensearchtest \
          -e "discovery.type=single-node" \
          -e "cluster.name=docker-cluster" \
          -e "http.cors.enabled=true" \
          -e "http.cors.allow-origin=*" \
          -e "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization" \
          -e "http.cors.allow-credentials=true" \
          -e "DISABLE_SECURITY_PLUGIN=true" \
          -e "DISABLE_INSTALL_DEMO_CONFIG=true" \
          -e "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" \
          -p 9200:9200 \
          -p 9600:9600 \
          opensearchproject/opensearch:2.12.0; \
          docker start opensearchtest; \
          docker exec opensearchtest /bin/sh -c "bin/opensearch-plugin install ingest-attachment -b"; \
          docker restart opensearchtest

      - name: Setup Plone ${{ matrix.plone }} with Python ${{ matrix.python }}
        id: setup
        uses: plone/setup-plone@v1.0.0
        with:
          python-version: ${{ matrix.python }}
          plone-version: ${{ matrix.plone }}

      - name: Install package
        run: |
          pip install -e ".[test, redis]"

      # test
      - name: test
        run: |
          zope-testrunner --auto-color --auto-progress --test-path src
